### ISSUE TITLE
Links of the lattes

### ISSUE THREAD

**Issue by araujodavid** [InsightLab/insightlab.github.io#1]
Add in the profile of the fellows the link to the Lattes.

**Comment by emanueloliveira23** [comment]
The links will be provided by each one or will be searched by user assigned to this issue?

**Comment by araujodavid** [comment]
To be faster we can search. I help and those we do not find we ask.

**Comment by emanueloliveira23** [comment]
Ok.

**Comment by araujodavid** [comment]
- Me: http://lattes.cnpq.br/4509694965806209
- Prof. Tonho: http://lattes.cnpq.br/5801731850423324
- Igo: http://lattes.cnpq.br/2100592282487417
- Francesco: http://lattes.cnpq.br/7824362088476452

To be continued...
