### ISSUE TITLE
Upload de apresentação: TrajectMe

### ISSUE THREAD

**Issue by emanueloliveira23** [InsightLab/insightlab.github.io#4]
@araujodavid ,

Segue o link da apresentação do TrajectMe. Você pode baixá-la e colocá-la no serviço que você usa.

[Apresentação TrajectMe](https://drive.google.com/file/d/1s8WjnLwqHe64An-64jYVBew-K_bZV3ro/view?usp=sharing)

**Comment by emanueloliveira23** [comment]
@araujodavid ,

Quando você subir, responde aqui com o link que ficou no serviço.

**Comment by emanueloliveira23** [comment]
@araujodavid ,

Segue o resumo da apresentação:

`In this article, we propose TrajectMe, an algorithm that solves the orienteering problem with hotel selection in several cities, taking advantage of the tourists' trajectories extracted from location-based services. This method is an extension of the state-of-the-art memetic-based algorithm. 
To this end, we collect data from Foursquare and Flickr location-based services, reconstruct the trajectories of tourists. Next, we build a hotel graph model (HGM) using a set of trajectories and a set of hotels to infer typical sequences of hotels and point of interest (PoI). 
The HGM is applied in the initialization phase and in the genetic operations of the memetic algorithm to provide good sequences of hotels, whereas the associated sequence of PoIs are improved by applying local search moves.
We evaluate our proposal using a large and real dataset from three Italian cities using up to 1000 hotels. The results show that our approach is effective and outperforms the state-of-the-art when using large real datasets. Our approach is better than the baseline algorithm by up to 208% concerning the solution score and proved to be more profitable toward PoI visiting time, being 54% better than state-of-the-art.`

**Comment by araujodavid** [comment]
Segue @emanueloliveira23 

https://speakerdeck.com/_insightlab/trajectme-planning-sightseeing-tours-with-hotel-selection-from-trajectory-data
